import React from 'react';
import { Card } from '../components/ui/Card';

export const TermsOfService: React.FC = () => (
    <div className="w-full max-w-4xl mx-auto py-12 px-4 animate-fade-in">
        <Card className="text-left">
            <h1 className="text-4xl font-extrabold text-gray-900 mb-6">Terms of Service</h1>
            <div className="prose prose-lg text-gray-700 max-w-none space-y-4">
                <p><em>Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</em></p>
                <p>By accessing and using NutriLens ("Service"), you agree to be bound by these Terms of Service ("Terms"). Please read them carefully.</p>

                <h2 className="text-2xl font-bold text-gray-800 !mt-8 !mb-3">1. Use of Service</h2>
                <p>NutriLens provides nutritional analysis of food images for informational purposes only. The information generated by the AI is an estimate and should not be considered a substitute for professional medical advice, diagnosis, or treatment. You should always consult with a qualified healthcare professional before making any significant dietary changes.</p>
                
                <h2 className="text-2xl font-bold text-gray-800 !mt-8 !mb-3">2. User Accounts</h2>
                <p>You are responsible for safeguarding your account information. You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account. You must be at least 13 years old to use the Service.</p>

                <h2 className="text-2xl font-bold text-gray-800 !mt-8 !mb-3">3. User Content</h2>
                <p>You retain all your rights to any content you submit, post or display on or through the Service (e.g., uploaded images). By submitting content, you grant us a worldwide, non-exclusive, royalty-free license to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute such content in any and all media or distribution methods, solely for the purpose of providing and improving the Service.</p>

                <h2 className="text-2xl font-bold text-gray-800 !mt-8 !mb-3">4. Disclaimer</h2>
                <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. NutriLens makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. We do not warrant that the nutritional information provided will be 100% accurate.</p>
                
                <h2 className="text-2xl font-bold text-gray-800 !mt-8 !mb-3">5. Limitation of Liability</h2>
                <p>In no event shall NutriLens or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on NutriLens's website, even if NutriLens or an NutriLens authorized representative has been notified orally or in writing of the possibility of such damage.</p>
                
                <h2 className="text-2xl font-bold text-gray-800 !mt-8 !mb-3">6. Governing Law</h2>
                <p>These terms and conditions are governed by and construed in accordance with the laws of our jurisdiction and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>
            </div>
        </Card>
    </div>
);